// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// AverageLoadingStorage is an autogenerated mock type for the AverageLoadingStorage type
type AverageLoadingStorage struct {
	mock.Mock
}

// SaveAnalyticsData provides a mock function with given fields: reportName, loadDuration
func (_m *AverageLoadingStorage) SaveAnalyticsData(reportName string, loadDuration time.Duration) {
	_m.Called(reportName, loadDuration)
}

// NewAverageLoadingStorage creates a new instance of AverageLoadingStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAverageLoadingStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *AverageLoadingStorage {
	mock := &AverageLoadingStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
